services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activio-backend
    entrypoint: ["./main"]
    ports:
      - "3000:8080"
    volumes: # Mount images folder
      - ./images:/go/src/app/images