name: Activio-Backend Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: activio-backend
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips-dev --no-install-recommends
        go mod download
        PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
        pkg-config --libs vips

    - name: Build App
      run: go build -v ./...

#     - name: Test App
#       run: go test -v ./...
